### ISSUE TITLE
Invalid labels are still being considered visible & draw happens unnecessarily for invalid labels

### ISSUE THREAD

**Issue by channeladam** [visjs-community/visjs-network#44]
When Label is initialised with an invalid label (such as an empty string), the visible() function still says that it is visible.

Similarly, the draw() function does not short-circuit when the label is invalid.

The root cause is Label.js line 42 which sets options.label to an empty string.
Both the visible and draw functions are checking for undefined, not empty string - so that is why they don't work as expected.

Label.js:
    if (ComponentUtil.isValidLabel(options.label)) {
      this.labelDirty = true
    } else {
      // Bad label! Change the option value to prevent bad stuff happening
      options.label = ''  **************** THIS IS THE PROBLEM - SHOULD BE undefined **************
    }

PR coming.

**Comment by mojoaxel** [comment]
:love_letter: Thanks @channeladam for your contribution!
This pull-request has been merge into https://github.com/visjs/vis-network/pull/26
