### ISSUE TITLE
Built JS and CSS files missing

### ISSUE THREAD

**Issue by dfritsch86** [visjs-community/visjs-network#61]
There is currently no "dist" folder with the complete JS and CSS files for the library. All examples reference these, but they do not exist.

Please consider re-adding them.

**Comment by micahstubbs** [comment]
hi @dfritsch86, thanks for using visjs-network!

You can run a local build with the `yarn build` command to generate the `dist` folder. 

We intentionally git-ignore this directory, on the principle that built artifacts should be committed to version control. https://github.com/visjs-community/visjs-network/blob/master/.gitignore#L2

That said, I understand how it may not be clear that new users need to first run `yarn build` before the examples will render locally.  We should probably document this.
