### ISSUE TITLE
 Support Icon in Shape with Label - Implement almende/vis#3743?

### ISSUE THREAD

**Issue by mgobishop** [visjs-community/visjs-network#63]
Support Icon in Shape with Label - Implement almende/vis#3743?

Assuming master doesn’t include almende/vis#3743? 

An icon inside a shape would be a game changer visually for the networks I’m creating using vis!

![34217640-feb47944-e579-11e7-8852-6523ffae91a9](https://user-images.githubusercontent.com/2119400/56860551-a77e1600-694c-11e9-95c9-880ea283c1b3.png)

**Comment by micahstubbs** [comment]
thanks for the suggestion @mgobishop!

would be happy to review a PR for this enhancement 😄

**Comment by micahstubbs** [comment]
ah ok, it looks like the relevant almende/vis PR is here https://github.com/almende/vis/pull/3756

**Comment by micahstubbs** [comment]
@mgobishop good news, this feature is already support in **visjs-network/master**

if you compare the files from the PR from back in Jan 2018 https://github.com/almende/vis/pull/3756/files

with https://github.com/visjs-community/visjs-network you'll see that the new code for this feature is included 😄 

To verify this yourself, 

```
git clone git@github.com:visjs-community/visjs-network.git
cd visjs-network
yarn 
yarn examples
```

then visit the example at http://127.0.0.1:8080/examples/nodeStyles/shapes/

![Screen Shot 2019-04-28 at 12 34 07 AM](https://user-images.githubusercontent.com/2119400/56860627-82d66e00-694d-11e9-8725-d896d1cb9a04.png)

will go ahead and close this one, thanks for the question!

**Comment by mgobishop** [comment]
Fantastic! I now have it working - thank you so much for your help! Is the plan to replace the vis docs (and website?) with yours?

**Comment by micahstubbs** [comment]
@mgobishop yes, we plan to host the docs and website for the new project soon.  In the meantime, we still link back to the old project's site and docs.

let me know if you'd like to help out with getting the new docs & examples site up 😄

**Comment by conor909** [comment]
Any plans to support these features for nodes on edges too?  I'd like to include images or icons along with text in my edge labels

**Comment by micahstubbs** [comment]
hi @conor909 good question.  I'd be happy to review a PR that contributed these features.  I don't have plans to add them myself anytime soon.

**Comment by conor909** [comment]
@micahstubbs ok thanks, I'd happily do it if I can find the time
