### ISSUE TITLE
Setting hoverConnectedEdges to false causes node hover to stop working

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [visjs-community/visjs-network#64]
Having my interaction options set as 
```
interaction: {
    selectConnectedEdges: false,
    hideEdgesOnDrag: true,
    hover: true
}
```
lets me hover nodes, but it hovers the edges as well.

Setting it to:

```
interaction: {
    selectConnectedEdges: false,
    hideEdgesOnDrag: true,
    hover: true,
    hoverConnectedEdges: false
}
```

Causes node and edge hover to stop.

**Comment by micahstubbs** [comment]
hi @Tyler-Maclachlan, thanks for reporting this one!

curious, could you share an example that reproduces the bug?  if you can make the example by modifying one of the existing examples, that would be most helpful!

https://github.com/visjs-community/visjs-network/tree/master/examples

**Comment by Tyler-Maclachlan** [comment]
Hi @micahstubbs,

So it seems if I hover the edge and go straight from the edge to the node then the node hover works. If I try hover a node without first hovering a connected edge it does not work.

Here is a link to jsbin using the Basic Usage example: [bin](https://jsbin.com/voritexeru/edit?html,js,output)

I wasn't 100% sure how to get a cdn for vis-network working.

**Comment by Tyler-Maclachlan** [comment]
Hi @micahstubbs,

I have submitted a PR that fixes this issue.
