### ISSUE TITLE
Dynamically change cluster edge colours

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [visjs-community/visjs-network#65]
Hi there,

@micahstubbs is there a way to dynamically change clustered edge colours, not the edges within the cluster, but the actual cluster edges?

I am using hover effects to highlight the path from one node to another and while I can get the normal edge colours to dynamically change I can't get the clustered edge colours to change.

**Comment by Tyler-Maclachlan** [comment]
@micahstubbs 

Would adding the following to clustering work for the above?
```
updateClusterEdge(clusterEdgeId, newOptions) {
    if (clusterEdgeId === undefined) {
      throw new Error('No clusterEdgeId supplied to updateClusterEdge.')
    }
    if (newOptions === undefined) {
      throw new Error('No newOptions supplied to updateClusterEdge.')
    }
    if (this.body.edges[clusterEdgeId] === undefined) {
      throw new Error('The clusterEdgeId supplied to updateClusterEdge does not exist.')
    }

    var edge = this.body.edges[clusterEdgeId];
    edge.setOptions(newOptions);
    this.body.emitter.emit('_dataChanges')
  }
```

**Comment by micahstubbs** [comment]
good question, will take a look

**Comment by Tyler-Maclachlan** [comment]
I tried this, didn't work, but updateEdge worked so I don't think this is needed.

**Comment by micahstubbs** [comment]
thanks for sharing what you found out @Tyler-Maclachlan!
