### ISSUE TITLE
Network - does updating an edge cause it to reset automatically in Hierarchical view?

### ISSUE THREAD

**Issue by DarylMcCullough** [visjs-community/visjs-network#67]
This bug was reported for vis.js, but was never resolved, as far as I know. I believe that it is still a bug for visjs-network, as well.

https://github.com/datastorm-open/visNetwork/issues/162

The behavior is the following: For a very simple network with one hidden edge, if you change the shape of the network manually by dragging a node, then the network will reset to the original position. A working example is here:

[javascript-example-from-visjs.zip](https://github.com/visjs-community/visjs-network/files/3258388/javascript-example-from-visjs.zip)

Open the html file test.html. You'll see a tiny network with three nodes. Drag the node in the lower left to a new position farther right. If you then hover over the node with your mouse, the network will reset to its original shape.

**Comment by DarylMcCullough** [comment]
I looked at the javascript code, and apparently the line that is causing the problem is this one (in  lib/network/modules/components/Edge.js,)

`if (options.hidden !== undefined || options.physics !== undefined) {
        dataChanged = true;
      }`

I'm not sure why this line is there. It seems that it should only be if options.hidden has changed, not if it's been set.

**Comment by micahstubbs** [comment]
hi @DarylMcCullough, thanks for reporting this one!  

I'd be happy to review a pull request if you would like to submit the fix, along with an example that shows the bug (and the fix).

**Comment by DarylMcCullough** [comment]
I created an example, which I put into the "test" folder. I created a pull request.
--Daryl
    On Saturday, June 8, 2019, 11:46:25 PM EDT, Micah Stubbs <notifications@github.com> wrote:  
 
 
hi @DarylMcCullough, thanks for reporting this one!

I'd be happy to review a pull request if you would like to submit the fix, along with an example that shows the bug (and the fix).

**Comment by micahstubbs** [comment]
Thanks for sending the PR!  I hope to review the PR and get it in sometime over the upcoming July 4th holiday.
