### ISSUE TITLE
Cannot use DataView for edges

### ISSUE THREAD

**Issue by bel0v** [visjs-community/visjs-network#75]
Hi!
DataSet works fine for edges, but when I try to use DataView, I get a `TypeError: edgesData.forEach is not a function`. The problem might be that DataSet has forEach method in its prototype, while DataView does not.
The error occurs in [EdgesHandler.js](https://github.com/visjs-community/visjs-network/blob/83e5613a1ba541bebaf1c468ecf837addc46cd23/lib/network/modules/EdgesHandler.js#L487)

**Comment by bel0v** [comment]
As a quick fix we could check if `edgesData` is an instance of `DataView` and  call getDataSet() first.

As a more generic fix, I wonder if we could just copy the prototype implementation as it is done [in DataView init](https://github.com/visjs-community/visjs-network/blob/3a5d25522cc2fbc2e10f9acef77df1aa0332b440/lib/DataView.js#L394)

**Comment by micahstubbs** [comment]
ah, interesting.  @bel0v I would be happy to review a fix if you would like to send a PR 🙏 

the ideas you suggest sound promising.

**Comment by bel0v** [comment]
@micahstubbs could you review the PR please? 🙂
I decided to stick with ad-hoc fixes, looks safer to me.
